import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SideBar from '../components/SideBar'
import Chat from '../components/partials/_Chat'
import axios from 'axios'


function Home() 
{

  const component =
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <div className={styles.Discussion}>
        <div className={styles.SideBar}>
          <SideBar />
        </div>

        <Chat/>

        {/* {
          dataNotification.status ?
            <Notification data={dataNotification}></Notification>
          : null
        } */}
    </div>
  </>

  return component
}

// export async function getServerSideProps({req, res}) 
// {
//   let defunts = []

//   // try 
//   // {
//   //   const data = await axios.post("https://naledi-api.onrender.com/conversations",
//   //   {
//   //     title: "Parle moi de toi!",
//   //     userId: "64271baeb529b4d74f11677a"
//   //   },
//   //   {
//   //     headers:{
//   //       Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IisyNDM4MTg4NjA2NjMiLCJpYXQiOjE2ODAyODQ1OTB9.oBagIaEgRdg72eRG1zsXDYDk58OXZRUg3P68W6jmT7U",
//   //     }
//   //   })

//   //   // if(dataDefunts.data.data) defunts = dataDefunts.data.data
//   //   if(data.data) 
//   //   {
//   //     console.log(data.data);
//   //   }
//   //   else
//   //   {
//   //     console.log(data);
//   //   }
//   // } 
//   // catch(err) 
//   // {
//   //   console.error(err)
//   // }

//   return {
//     props: { defunts }
//   }
// }

export default Home
